[rospy.client][INFO] 2016-06-09 13:35:01,337: init_node, name[/base/gazebo_services], pid[21931]
[xmlrpc][INFO] 2016-06-09 13:35:01,337: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2016-06-09 13:35:01,338: Started XML-RPC server [http://cmeintel-desktop:40002/]
[rospy.impl.masterslave][INFO] 2016-06-09 13:35:01,338: _ready: http://cmeintel-desktop:40002/
[rospy.init][INFO] 2016-06-09 13:35:01,342: ROS Slave URI: [http://cmeintel-desktop:40002/]
[rospy.registration][INFO] 2016-06-09 13:35:01,342: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2016-06-09 13:35:01,342: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2016-06-09 13:35:01,442: registered with master
[rospy.rosout][INFO] 2016-06-09 13:35:01,442: initializing /rosout core topic
[rospy.rosout][INFO] 2016-06-09 13:35:01,466: connected to core topic /rosout
[rospy.internal][INFO] 2016-06-09 13:35:01,662: topic[/rosout] adding connection to [/rosout], count 0
[rospy.simtime][INFO] 2016-06-09 13:35:02,467: initializing /clock core topic
[rospy.simtime][INFO] 2016-06-09 13:35:02,490: connected to core topic /clock
[rosout][INFO] 2016-06-09 13:35:02,534: gazebo_services running
[rospy.internal][INFO] 2016-06-09 13:35:03,593: topic[/clock] adding connection to [http://cmeintel-desktop:41031/], count 0
[rospy.core][INFO] 2016-06-09 13:42:46,806: signal_shutdown [signal-2]
[rospy.internal][INFO] 2016-06-09 13:42:46,809: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2016-06-09 13:42:46,809: topic[/clock] removing connection to http://cmeintel-desktop:41031/
[rospy.topics][ERROR] 2016-06-09 13:42:46,810: Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 307, in close
    c.close()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 807, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.impl.masterslave][INFO] 2016-06-09 13:42:46,810: signal-2
[rospy.internal][WARNING] 2016-06-09 13:42:46,812: Unknown error initiating TCP/IP socket to cmeintel-desktop:50571 (http://cmeintel-desktop:41031/): Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 619, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.core][INFO] 2016-06-09 13:42:46,926: signal_shutdown [atexit]
